language: python
python:
  - "2.7"
#  - "3.2" failing - can't import pymysql as mysql
  - "3.3"
  - "3.4"
  - "3.5"
addons:
  postgresql: "9.6"
services:
  - postgresql
  - mysql
install:
  - pip install peewee psycopg2 pymysql colorama
script:
  - python test.py PostgreSQL
  - python test.py MySQL

